# -*- coding: utf-8 -*-
"""ECommerce Purchase project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/163_E8M2BVjuMYjvh6mbMCNkeCDM3-M_O

DATASET: https://www.kaggle.com/datasets/utkarsharya/ecommerce-purchases

DATASET : https://www.kaggle.com/datasets/utkarsharya/ecommerce-purchases
"""

import pandas as pd

data = pd.read_csv('Ecommerce Purchases')
data

"""# 1 . Display Top 10 Rows of the Dataset

"""

data.head(19)

"""# 2. Check Last 10 rows of the dataset"""

data.tail(10)

"""# 3. Check Datatypes of each column"""

data.dtypes

"""# 4. Check Null values in Daataset"""

data.isnull().sum()

"""# 5. How many Rows and Columns are there in our dataset"""

len(data.columns)

len(data)

data.info()

"""# 6. Highest and Lowest purchase Prices"""

data.columns

data['Purchase Price'].max()

data['Purchase Price'].min()

"""# 7. Average Purchase Price"""

data['Purchase Price'].mean()

"""#  8. How many people have french "fr" as their first language"""

data.columns

len(data[data['Language']=='fr'])

"""# 9. Job title contains "Engineer"
"""

data.columns

data['Job']

len(data[data['Job'].str.contains('engineer',case= False)])

"""# 10. How many people have master card as their credit card provider and have made a purchase of over 50"""

data.columns

len(data[(data['CC Provider'] == 'Mastercard') & (data['Purchase Price']>50)])

"""# 11.Find Email of the user with the following Credit card number 4664825258997302"""

data[data['Credit Card']==4664825258997302]['Email']

"""# 12. How many people purchase during the AM and how many people buy during PM"""

data.columns

data['AM or PM'].value_counts()

"""# 13. How many People have a credit card that expires in 2020"""

data.columns

data['CC Exp Date']

def fun():
  count = 0
  for date in data['CC Exp Date']:
    if date.split('/')[1] == '20':
      count=count+1
  print(count)

fun()

len(data[data['CC Exp Date'].apply(lambda x:x[3:]=='20')])